apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentservice-deployment
  labels:
    app: studentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentservice
  template:
    metadata:
      labels:
        app: studentservice
    spec:
      containers:
        - name: studentservice
          image: shawnpfiore/studentservice:latest
          ports:
            - containerPort: 4000


---

apiVersion: v1
kind: Service
metadata:
  name: studentservice
spec:
  selector:
    app: studentservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31110